<a href="https://colab.research.google.com/github/Leo278V/Final-Assignment-PDS/blob/Natural-Language-Processing-Model/Advanced_NLP_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:

data_path_profiles = "https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/Natural-Language-Processing-Model/df_profiles_cleansed.csv"
df_profiles = pd.read_csv(data_path_profiles)
df_profiles.head()

,organization,position,startDate,endDate,status,department,seniority,person_id,job_count,job_duration_years
0,Depot4Design GmbH,Prokurist,2019-08,2025-12,ACTIVE,Other,Management,0,6,6.339726
1,Depot4Design GmbH,CFO,2019-07,2025-12,ACTIVE,Other,Management,0,6,6.424658
2,Depot4Design GmbH,Betriebswirtin,2019-07,2025-12,ACTIVE,Other,Professional,0,6,6.424658
3,Depot4Design GmbH,Prokuristin,2019-07,2025-12,ACTIVE,Other,Management,0,6,6.424658
4,Depot4Design GmbH,CFO,2019-07,2025-12,ACTIVE,Other,Management,0,6,6.424658

In [3]:
#Check for missing values

df_profiles.isna().sum()

organization          0
position              0
startDate             0
endDate               0
status                0
department            0
seniority             0
person_id             0
job_count             0
job_duration_years    0
dtype: int64

In [4]:
#Check for type of values

df_profiles["status"].value_counts(dropna=False)

status
INACTIVE    1897
ACTIVE       718
Name: count, dtype: int64

In [5]:
# Seniority CSV
data_path_seniority = "https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/Final-Assignment-V2/seniority-v2.csv"
df_seniority = pd.read_csv(data_path_seniority)
df_seniority.head()

                                text   label
0                            Analyst  Junior
1                 Analyste financier  Junior
2  Anwendungstechnischer Mitarbeiter  Junior
3               Application Engineer  Senior
4              Applications Engineer  Senior

In [7]:
#Checking for missing values
df_seniority.isna().sum()

text     0
label    0
dtype: int64

In [9]:
df_seniority.shape

(9428, 2)

In [6]:
# Department CSV
data_path_department = "https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/Final-Assignment-V2/department-v2.csv"
df_department = pd.read_csv(data_path_department)
df_department.head()

                                               text               label
0                   Adjoint directeur communication           Marketing
1                     Advisor Strategy and Projects  Project Management
2                               Beratung & Projekte  Project Management
3                      Beratung & Projektmanagement  Project Management
4  Beratung und Projektmanagement kommunale Partner  Project Management

In [8]:
#Checking for missing values
df_department.isna().sum()

text     0
label    0
dtype: int64

In [10]:
df_department.shape

(10145, 2)