<a href="https://colab.research.google.com/github/Leo278V/Final-Assignment-PDS/blob/Final-Assignment/Final_Assignment_PDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data_path_department = 'https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/main/department-v2.csv?token=GHSAT0AAAAAADQCRM6XOPWYN6PDRNFRGVSO2JXGNFA'
df_1 = pd.read_csv(data_path_department)
df_1.head()

                                               text               label
0                   Adjoint directeur communication           Marketing
1                     Advisor Strategy and Projects  Project Management
2                               Beratung & Projekte  Project Management
3                      Beratung & Projektmanagement  Project Management
4  Beratung und Projektmanagement kommunale Partner  Project Management

In [ ]:
data_path_seniority = 'https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/main/seniority-v2.csv?token=GHSAT0AAAAAADQCRM6XX5JQJYZAJOV4W4YA2JXGQFQ'
df_2 = pd.read_csv(data_path_seniority)
df_2.head()

                                text   label
0                            Analyst  Junior
1                 Analyste financier  Junior
2  Anwendungstechnischer Mitarbeiter  Junior
3               Application Engineer  Senior
4              Applications Engineer  Senior

In [ ]:
data_path_test_data = 'https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/main/linkedin-cvs-annotated.json?token=GHSAT0AAAAAADQCRM6WUKLL4CIMZH6FBEA62JXHV3Q'
df_3 = pd.read_json(data_path_test_data)
df_3.head()

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,"{'organization': 'Depot4Design GmbH', 'linkedi...","{'organization': 'Depot4Design GmbH', 'linkedi...","{'organization': 'Depot4Design GmbH', 'linkedi...","{'organization': 'Depot4Design GmbH', 'linkedi...","{'organization': 'Depot4Design GmbH', 'linkedi...","{'organization': 'Nagel Car Group', 'linkedin'...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"{'organization': 'Computer Solutions', 'linked...","{'organization': 'Computer Solutions', 'linked...",{'organization': 'Texas A&M University-Corpus ...,{'organization': 'Texas A&M University-Corpus ...,{'organization': 'Texas A&M University at Qata...,{'organization': 'Texas A&M University at Qata...,"{'organization': 'Texas A&M Forest Service', '...","{'organization': 'MicroAge College Station', '...",None,None,...,None,None,None,None,None,None,None,None,None,None
2,"{'organization': 'Udo Weber', 'linkedin': 'htt...","{'organization': 'Med 360°', 'linkedin': 'http...","{'organization': 'Philips', 'linkedin': 'https...",None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"{'organization': 'Grupo Viajes Kontiki.', 'lin...",{'organization': 'Air & Ground Operations Cons...,"{'organization': 'Viajes Oceano S.L.', 'linked...",{'organization': 'TDCS Travelport official par...,"{'organization': 'Smyland, Logitravel group', ...",{'organization': 'Confederación Española de Ag...,"{'organization': 'Vik Hotel Group', 'linkedin'...",None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,{'organization': 'Himmelstalunds Utbildningsce...,"{'organization': 'ABC Kraften', 'linkedin': 'h...","{'organization': 'Trind AB', 'linkedin': '', '...","{'organization': 'Telia Company', 'linkedin': ...","{'organization': 'Telia Company', 'linkedin': ...","{'organization': 'TeliaSonera', 'linkedin': ''...","{'organization': 'Telia Communications', 'link...","{'organization': 'Telia AB', 'linkedin': '', '...",None,None,...,None,None,None,None,None,None,None,None,None,None